# configuration file for ep3.py

#------------------------------------------------------------------------------
# Metadata
#------------------------------------------------------------------------------

title:          Uncharted
# subtitle:
author:         Anna Lowe
authorweb:      www.annalowebooks.com
authoremail:    author@annalowebooks.com
# authorlist:
series:         A Serendipity Adventure romance
publisher:      Twin Moon Press
pubdate:        2015-07-30
editor:
    name:       Erika Mustermann
    web:        http://www.erika.com
coverart:
    name:       Fiona Jayde Media
    web:        www.FionaJaydeMedia.com

blurb: >
    Don’t despair! Our Wicked Alphas are about to get even wilder
    in a second sizzling collection heading your way soon. {ww2_link_snippet}
    releases on October 30, 2015 and features ALL-NEW, previously
    unpublished scenes from your favorite paranormal romance authors,
    including New York Times and USA Today bestsellers. We’re writing red-hot
    scenes with werewolves, shapeshifting bears, ghosts, and more just for
    this great new collection!

keywords:
    - Romance
    - Paranormal

#------------------------------------------------------------------------------
# Book contents
#------------------------------------------------------------------------------
# book will be assembled as
# - cover page (not listed in this file)
# - frontmatter
# - toc (not listed in this file)
# - mainmatter
# - backmatter

# label for each item will become page-id with href={label}.xhtml
# for type == template a template {label}.jinja must exist in templates folder
frontmatter:
    - title:
        type:   template
    - copyright:
        type:   template
    - freebook:
        type:   static
    - booksinseries:
        type:   static

backmatter:
    - otherbooksbyauthor:
        type:   static
    - recommendedreads:
        type:   static
    - sneakpeek1:
        type:   static
    - sneakpeek2:
        type:   static
    - morefromauthor:
        type:   static

mainmatter:




