#==============================================================================
# Configuration file for scriv2epub - see README.md for genral intro
#==============================================================================

#------------------------------------------------------------------------------
# Metadata
#------------------------------------------------------------------------------

title:          This is the Title
# subtitle:     # uncommen if you want this to appear
subplain:       Comment this out if you don't wnat it to appear
author:         Fred Feuerstein
authorweb:      www.fredfeuerstein.com      # will not be linked
authoremail:    fred@feuerstein.com
# authorlist:
#  - author one # uncomment if you want multiple author to appear as
                # creators in content.opf
#  - author two
series:         The Flintstones
publisher:      Blue Moon Press
pubdate:        YYYY-MM-DD      # needs to be in this format
editor:         # comment out / delete if not to appear
    name:       Ed Itor
    web:        www.EdItor.com              # will not be linked
coverart:       # comment out / delete if not to appear
    name:       Art Ist
    web:        www.ArtIts.com              # will not be linked

description: >
    Put blurb / description here. Can be multiple lines (all
    lines must be indented equally, will be unwrapped before inserting into
    templates).

keywords:
    - Neanderthal
    - Romance

#------------------------------------------------------------------------------
# Book contents
#------------------------------------------------------------------------------
# Book will be assembled as
# - frontmatter (incl. cover page)
# - mainmatter (defined in separate YAML file)
# - backmatter

# For opf guide section: id of page to open to:
start_id:   title

# Label for each item will become page-id with href={label}.xhtml
# For type == template a template {id}.jinja must exist in templates folder
# `type` attribute:
#       static      -   a file {id}.xhtml will be copied from source to target
#                       directory (source and target can be specified as cmd
#                       line parameters)
#       template    -   either a template {id}.jinja must exist in templates
#                       folder or a 'template' attribute must provide the name
#                       of the template to be used (without .ninja suffix); an
#                       additional top-level YAML section can be provided to
#                       specify the page contents (see example below); the root
#                       of the data structure generated from this YAML will be
#                       passed into the template as the pg_data variable; the
#                       YAML section can also be offshored into a separate YAML
#                       file named {id}.yaml in a directory specified by the
#                       --yincl parameter to s2e's `genep` command
#       chapter     -   will  generate xhtml content from {id}.md in
#                       source directory and use 'chapter.jinja' in templates
#                       directory unless another template is specified; the
#                       dict with the page parameters and the xhtml content
#                       from the source Markdown file will be passed into the
#                       template
#
frontmatter:
    - id:       cover
      type:     static
      heading:  Cover Page
    - id:       title
      type:     template
      heading:  Titel Page
    - id:       copyright
      type:     template
      heading:  Copyright
    - id:       freebook_dd
      type:     static
      heading:  Free Book
    - id:       booksinseries
      # pg_data will be taken from 'booksinseries' section in this file is
      # avilable or read from booksinseries.yaml
      type:     template
      template: book_list
      heading:  Other books in this series
      url:      http://fredfeuerstein.com       # will appear at bottom of list
                                                # id specified
      urltext:  www.FredFeuerstein.com
    - id:       toc
      type:     template
      heading:  Contents

booksinseries:  # if provided in separate file, list starting with '- name'
                # must be at top level; see comments in book_list.jinja
                # for avialable variables
- series:     Some Series Title
  titlelist:
  - title:    Blue Moon
    tclause:  (Book 1)
    url:      http://...
  - title:    Yellow Moon
    tclause:  (the Prequel)
    url:      http://...
  addonsep:   'coming soon:'
  addons:
  - title:    Distant Sun
    tclause:  (Book 2)
    url:      http://...
- series:     Some other Series Title
  titlelist:
  - title:    Deep Sea
    tclause:  (Book 1)
    url:      http://...
  - title:    Shallow Water
    tclause:  (the Prequel)
    url:      http://...

backmatter:
    - id:       otherbooksbyauthor
      # pg_data will be read from otherbooksbyauthor.yaml
      type:     template
      template: book_list
      heading:  Other Books by the Author
      url:      http://fredfeuerstein.com
      urltext:  www.FredFeuerstein.com
    - id:       recommendedreads
      type:     static
      heading:  Recommended Reads
